version: 2

project_name: picoclaw-dashboard

# Disable standard semver requirements for 'fork-X' tags
builds:
  - id: picoclaw-dashboard
    binary: picoclaw-dashboard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
